import { Router } from 'express';
import authRoutes from './auth.routes.js';
import productRoutes from './product.routes.js';
import vendorRoutes from './vendor.routes.js';
import cartRoutes from './cart.routes.js';
import orderRoutes from './order.routes.js';
import paymentRoutes from './payment.routes.js';
import aiRoutes from './ai.routes.js';
import adminRoutes from './admin.routes.js';
const router = Router();
router.get('/health', (_req,res)=>res.json({ success:true, message:'THE MARKET PLACE API is healthy', data:{ uptime:process.uptime() } }));
router.use('/auth', authRoutes);
router.use('/products', productRoutes);
router.use('/vendors', vendorRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/ai', aiRoutes);
router.use('/admin', adminRoutes);
export default router;
