import express from 'express';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import compression from 'compression';
import morgan from 'morgan';
import swaggerUi from 'swagger-ui-express';
import swaggerJsdoc from 'swagger-jsdoc';
import { env } from './config/env.js';
import routes from './routes/index.js';
import { apiLimiter, helmetMiddleware, sanitizeMiddleware } from './middleware/security.js';
import { errorHandler, notFound } from './middleware/error.js';
export const app = express();
app.set('trust proxy', 1);
app.use(helmetMiddleware);
app.use(cors({ origin: env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(compression());
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(apiLimiter);
app.use(sanitizeMiddleware);
const spec = swaggerJsdoc({ definition: { openapi:'3.0.0', info:{ title:'THE MARKET PLACE API', version:'1.0.0' } }, apis:['./src/routes/*.ts'] });
app.use('/api/docs', swaggerUi.serve, swaggerUi.setup(spec));
app.use('/api/v1', routes);
app.use(notFound);
app.use(errorHandler);
